[config]
version_check = false

# Waybar
[templates.waybar]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.config/waybar/matugen-waybar.css'
post_hook = 'pkill -SIGUSR2 waybar'
